-- Local SQLite version of 12_transaction_list.sql
-- Source: Supabase SQL/12_transaction_list.sql
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS transaction_list (


  -- UUID v7 primary key, generated client-side for offline support; no DEFAULT
  -- Printed on receipts as the unique transaction reference
  -- UUID v7 主键，由客户端生成，支持离线；不设 DEFAULT
  -- 小票上会打印本 ID 作为交易唯一凭证
  transaction_id text PRIMARY KEY,

  -- Store ID, FK to store_list
  -- 门店 ID，外键指向 store_list
  store_id text NOT NULL REFERENCES store_list(store_id),

  -- Customer ID (UUID), FK to customer_list; NULL = walk-in customer
  -- 客户 ID（UUID），外键指向 customer_list；NULL 表示散客
  customer_id text DEFAULT NULL REFERENCES customer_list(customer_id),

  -- Employee who processed this transaction, FK to user_list
  -- 经手人 ID，外键指向 user_list；每笔交易应有经手人
  user_id integer NOT NULL REFERENCES user_list(user_id),

  -- Human-readable document number for receipts
  -- Format: {store_code}{device_no}S-{YYMMDD}-{NNN} (e.g. D2S-260303-003)
  -- NULL allowed for legacy rows / offline temp rows before server normalization
  -- 小票可读单号
  -- 格式：{store_code}{device_no}S-{YYMMDD}-{NNN}（例如 D2S-260303-003）
  -- 兼容历史数据与离线临时记录：允许为 NULL
  display_no text DEFAULT NULL,

  -- Legacy per-store sequential integer (kept for backward compatibility)
  -- 历史整型展示编号（为兼容旧逻辑保留）
  store_transaction_id integer DEFAULT NULL,

  -- Batch ID (must be assigned before creating a transaction)
  -- 批次 ID（创建交易前必须先分配）
  batch_id integer NOT NULL,

  -- Shift ID (must be assigned before creating a transaction)
  -- 班次 ID（创建交易前必须先分配）
  shift_id integer NOT NULL,

  -- Related transaction ID: for refund/exchange, points to the original transaction
  -- No FK constraint: the original transaction may not yet be synced (offline scenario)
  -- 关联交易 ID：退货/换货时指向原交易的 transaction_id
  -- 不加外键约束：关联的原交易可能尚未同步到服务端（离线场景）
  related_transaction_id text DEFAULT NULL,

  -- Transaction type, determined by client using priority rules (see ENUM above)
  -- 交易类型，由客户端根据优先级规则判定（参见上方枚举）
  type text NOT NULL,

  -- Last edit timestamp; NULL = never edited, non-NULL = time of most recent edit
  -- 编辑时间戳；NULL 表示未编辑过，有值 = 最近一次编辑时间
  edited_at text DEFAULT NULL,

  -- =============================================
  -- Payment method breakdown (all NOT NULL DEFAULT 0)
  -- 支付方式金额明细（均 NOT NULL DEFAULT 0）
  -- =============================================

  -- Cash payment amount
  -- 现金支付金额
  cash numeric NOT NULL DEFAULT 0,

  -- Credit card payment amount
  -- 信用卡支付金额
  credit numeric NOT NULL DEFAULT 0,

  -- Debit card payment amount
  -- 借记卡支付金额
  debit numeric NOT NULL DEFAULT 0,

  -- Amount paid from customer's store balance
  -- 从客户余额中扣除的金额
  balance numeric NOT NULL DEFAULT 0,

  -- =============================================
  -- Summary amounts (all NOT NULL DEFAULT 0)
  -- 汇总金额（均 NOT NULL DEFAULT 0）
  -- =============================================

  -- Transaction total = cash + credit + debit + balance (validated by CHECK below)
  -- 交易总额 = cash + credit + debit + balance（由下方 CHECK 约束校验）
  amount_total numeric NOT NULL DEFAULT 0,

  -- Total tax amount
  -- 税额合计
  tax_total numeric NOT NULL DEFAULT 0,

  -- Total cost (even for payment-type transactions, cost remains 0, not NULL)
  -- 成本合计（即使是 payment 类型，cost 仍为 0，不为 NULL）
  cost_total numeric NOT NULL DEFAULT 0,

  -- Profit = amount_total - tax_total - cost_total (validated by CHECK below)
  -- 利润 = amount_total - tax_total - cost_total（由下方 CHECK 约束校验）
  profit_total numeric NOT NULL DEFAULT 0,

  -- =============================================
  -- Notes / 备注
  -- =============================================

  -- Note printed on the customer receipt (customer-visible)
  -- 打印在小票上的备注（客户可见）
  note_on_receipt text DEFAULT NULL,

  -- Internal system note (staff-only, not printed)
  -- 系统内部备注（仅员工可见，不打印）
  note_on_system text DEFAULT NULL,

  -- =============================================
  -- Device / 设备
  -- =============================================

  -- Device ID: generated by the client on first launch and permanently saved
  -- 设备 ID：客户端首次启动时生成并永久保存
  device_id text DEFAULT NULL,

  -- repair_ticket_id will be added by ALTER TABLE in file 22_repair_ticket_list
  -- repair_ticket_id 将在 22_repair_ticket_list 中通过 ALTER TABLE 添加

  -- =============================================
  -- Timestamps / 时间戳
  -- =============================================

  -- Client-side creation timestamp (provided by client for offline scenarios)
  -- 客户端本地创建时间（离线场景下由客户端提供）
  created_at text NOT NULL,

  -- First sync timestamp to Supabase; NULL = not yet synced
  -- 首次同步到 Supabase 的时间；NULL 表示尚未同步
  synced_at text DEFAULT NULL,

  -- Last update timestamp (auto-refreshed by set_updated_at() trigger)
  -- 最后更新时间（由 set_updated_at() 触发器自动刷新）
  updated_at text NOT NULL,

  -- Soft delete timestamp; NULL = active, non-NULL = voided
  -- 软删除时间戳；NULL 表示正常，非 NULL 表示已作废
  deleted_at text DEFAULT NULL,

  -- =============================================
  -- CHECK constraints: validate client-side calculations to prevent dirty data
  -- 兜底校验：确保客户端计算正确，阻止脏数据入库
  -- =============================================

  -- CHECK: amount_total must equal the sum of all payment methods
  -- 约束：交易总额必须等于所有支付方式之和
  CONSTRAINT chk_transaction_list_amount_total
    CHECK (amount_total = cash + credit + debit + balance),

  -- CHECK: profit_total must equal amount_total minus tax and cost
  -- 约束：利润必须等于总额减去税和成本
  CONSTRAINT chk_transaction_list_profit_total
    CHECK (profit_total = amount_total - tax_total - cost_total)

  -- Optional format guard for display_no
  -- 显示单号格式校验（可空）
);
