-- Last updated (America/Toronto): 2026-03-07 10:55:46 EST
-- 最后更新时间（蒙特利尔时区）: 2026-03-07 10:55:46 EST
-- Async requirement: NO - cloud-first event log table; offline clients keep local outbox and sync to this cloud table after reconnection.
-- 异步需求：否 - 云端优先事件日志表；离线客户端在本地 outbox 暂存，联网后同步到本表。
-- =============================================
-- File 26 · sync_changes — Business sync event log table
-- 文件 26 · sync_changes — 业务同步事件日志表
-- =============================================
-- Dependencies / 依赖:
--   01_store_list (source_store_id / target_store_id FK)
-- Dependents / 被依赖:
--   (none currently)
--   （当前无）
-- Shared components created here / 本文件创建的共享组件:
--   ENUM public.sync_event_type — this table only
--   Function public.block_sync_changes_mutation() — this table only
-- =============================================
-- Design contract / 设计约定:
--   1) One completed business action = one sync_changes row.
--      一次完整业务动作 = 一条 sync_changes 记录。
--   2) event_id must be idempotent and unique (client-side generated).
--      event_id 必须可幂等且唯一（客户端生成）。
--   3) Business write + sync_changes insert must be in the same DB transaction.
--      业务写入 + sync_changes 插入必须在同一数据库事务中提交。
-- =============================================

-- =============================================
-- ENUM: sync_event_type — Business event classification
-- 枚举：sync_event_type — 业务事件分类
-- =============================================
DO $$
BEGIN
  CREATE TYPE public.sync_event_type AS ENUM (
    'transaction_committed',
    'inventory_adjustment_committed',
    'purchase_order_received',
    'store_transfer_committed',
    'store_transfer_received',
    'repair_ticket_committed',
    'customer_updated',
    'supplier_updated',
    'misc_updated'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- =============================================
-- Function: block_sync_changes_mutation()
-- 函数：block_sync_changes_mutation()
-- =============================================
-- sync_changes is append-only; UPDATE/DELETE are blocked.
-- sync_changes 为追加型日志；禁止 UPDATE / DELETE。
CREATE OR REPLACE FUNCTION public.block_sync_changes_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'sync_changes is append-only; % is not allowed', TG_OP;
END;
$$;

-- =============================================
-- Table creation / 建表
-- =============================================
CREATE TABLE IF NOT EXISTS public.sync_changes (

  -- Global increasing cursor used by clients for pull-based incremental sync
  -- 全局递增游标，供客户端拉取增量同步使用
  change_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Idempotency key generated by client/local outbox event
  -- 幂等键，由客户端/本地 outbox 事件生成
  event_id text NOT NULL,

  -- Correlation key linking related events in one workflow chain
  -- 关联键，用于把同一业务链路的多条事件串联
  correlation_id text DEFAULT NULL,

  -- Business event type
  -- 业务事件类型
  event_type public.sync_event_type NOT NULL,

  -- One event may involve multiple primary entity IDs
  -- 一条事件可能涉及多个主实体 ID
  entity_ids text[] NOT NULL DEFAULT '{}'::text[],

  -- Target store that should consume this event; NULL = global event
  -- 目标门店（需要消费该事件）；NULL = 全局事件
  target_store_id text DEFAULT NULL REFERENCES public.store_list(store_id),

  -- Source store that produced this event
  -- 事件来源门店
  source_store_id text NOT NULL REFERENCES public.store_list(store_id),

  -- Source device identifier (text only; no FK by design)
  -- 来源设备标识（仅 text；按设计不加 FK）
  source_device_id text DEFAULT NULL,

  -- Event payload packet (recommended keys: event_type/entity_ids/store_scope/data/meta)
  -- 事件载荷（建议键：event_type/entity_ids/store_scope/data/meta）
  payload_json jsonb NOT NULL,

  -- Client-side business occurrence time
  -- 客户端业务发生时间
  occurred_at timestamptz NOT NULL DEFAULT now(),

  -- Cloud commit time when this event row is persisted
  -- 云端入库提交时间
  committed_at timestamptz NOT NULL DEFAULT now(),

  -- CHECK: event_id must not be blank
  -- 约束：event_id 不可为空白字符串
  CONSTRAINT chk_sync_changes_event_id_not_blank
    CHECK (length(btrim(event_id)) > 0),

  -- CHECK: source_store_id must not be blank
  -- 约束：source_store_id 不可为空白字符串
  CONSTRAINT chk_sync_changes_source_store_not_blank
    CHECK (length(btrim(source_store_id)) > 0),

  -- CHECK: payload_json should be a JSON object
  -- 约束：payload_json 应为 JSON 对象
  CONSTRAINT chk_sync_changes_payload_is_object
    CHECK (jsonb_typeof(payload_json) = 'object')
);

-- =============================================
-- Migration safety patch / 迁移兼容补丁
-- =============================================
ALTER TABLE public.sync_changes
  ADD COLUMN IF NOT EXISTS correlation_id text;

ALTER TABLE public.sync_changes
  ADD COLUMN IF NOT EXISTS occurred_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.sync_changes
  ADD COLUMN IF NOT EXISTS committed_at timestamptz NOT NULL DEFAULT now();

-- =============================================
-- Idempotency uniqueness / 幂等唯一性
-- =============================================
CREATE UNIQUE INDEX IF NOT EXISTS uq_sync_changes_event_id
  ON public.sync_changes (event_id);

-- =============================================
-- Indexes / 索引
-- =============================================

-- Main pull path: target store + cursor
-- 主要拉取路径：目标门店 + 游标
CREATE INDEX IF NOT EXISTS idx_sync_changes_target_store_change_id
  ON public.sync_changes (target_store_id, change_id);

-- Source tracing: source store + cursor
-- 来源追踪：来源门店 + 游标
CREATE INDEX IF NOT EXISTS idx_sync_changes_source_store_change_id
  ON public.sync_changes (source_store_id, change_id);

-- Commit-time descending timeline
-- 提交时间倒序时间线
CREATE INDEX IF NOT EXISTS idx_sync_changes_committed_at
  ON public.sync_changes (committed_at DESC);

-- Correlation lookup
-- 关联键查询
CREATE INDEX IF NOT EXISTS idx_sync_changes_correlation_id
  ON public.sync_changes (correlation_id)
  WHERE correlation_id IS NOT NULL;

-- Event type filtering
-- 按事件类型筛选
CREATE INDEX IF NOT EXISTS idx_sync_changes_event_type_change_id
  ON public.sync_changes (event_type, change_id);

-- Entity membership lookup
-- 实体 ID 数组包含关系查询
CREATE INDEX IF NOT EXISTS gin_sync_changes_entity_ids
  ON public.sync_changes USING gin (entity_ids);

-- =============================================
-- Triggers: block UPDATE/DELETE (append-only log)
-- 触发器：阻止 UPDATE/DELETE（追加型日志）
-- =============================================
DROP TRIGGER IF EXISTS trg_sync_changes_block_update ON public.sync_changes;
CREATE TRIGGER trg_sync_changes_block_update
BEFORE UPDATE ON public.sync_changes
FOR EACH ROW
EXECUTE FUNCTION public.block_sync_changes_mutation();

DROP TRIGGER IF EXISTS trg_sync_changes_block_delete ON public.sync_changes;
CREATE TRIGGER trg_sync_changes_block_delete
BEFORE DELETE ON public.sync_changes
FOR EACH ROW
EXECUTE FUNCTION public.block_sync_changes_mutation();
